# Generated by Django 5.1 on 2024-11-05 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerproperties',
            name='antivirus',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='computerproperties',
            name='name',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
