# Generated by Django 5.1 on 2024-11-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0004_rule_monitoreo'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerproperties',
            name='browser',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='computerproperties',
            name='antivirus',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='computerproperties',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
