# Generated by Django 5.1 on 2024-11-07 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0005_computerproperties_browser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerproperties',
            name='antivirus_scan_frequency',
        ),
        migrations.RemoveField(
            model_name='computerproperties',
            name='antivirus_update_frequency',
        ),
        migrations.RemoveField(
            model_name='computerproperties',
            name='password',
        ),
        migrations.RemoveField(
            model_name='computerproperties',
            name='user',
        ),
        migrations.AddField(
            model_name='computerproperties',
            name='firewall_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='computerproperties',
            name='browser',
            field=models.CharField(default='Firefox', max_length=255),
        ),
    ]
