# Generated by Django 5.1 on 2024-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0006_remove_computerproperties_antivirus_scan_frequency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo',
            name='computer',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='rule',
        ),
        migrations.RemoveField(
            model_name='monitoreo',
            name='status',
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='computers_monitored',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='incumplimientos_detected',
            field=models.IntegerField(default=0),
        ),
    ]
