# Generated by Django 5.1 on 2024-11-04 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0007_remove_monitoreo_computer_remove_monitoreo_rule_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitoreo',
            name='computers_monitored',
        ),
        migrations.AlterField(
            model_name='monitoreo',
            name='incumplimientos_detected',
            field=models.JSONField(),
        ),
        migrations.AddField(
            model_name='monitoreo',
            name='computers_monitored',
            field=models.ManyToManyField(to='Modulo.computerproperties'),
        ),
    ]
