# Generated by Django 5.1 on 2024-11-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modulo', '0008_remove_monitoreo_computers_monitored_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoreo',
            name='incumplimientos_detected',
            field=models.JSONField(default=list),
        ),
    ]
